### ISSUE TITLE
[Bug]: Error with Source Generator when using multiple types with the same name in different namespaces

### ISSUE THREAD

**Issue by Soar360** [reactiveui/ReactiveUI.SourceGenerators#131]
### Describe the bug 🐞

I'm encountering an issue with the `ReactiveUI.SourceGenerators` package (version 2.0.17) in my Avalonia project. After upgrading to this version, I receive the following warning during compilation:

```
warning CS8785: The generator "ReactiveGenerator" failed to produce source. This will not affect the output, but may cause compilation errors. The exception type is "ArgumentException", with the message "The hintName 'SearchTask' was added by source file, but the two types exist in different namespaces. .Properties.g.cs must be unique within the generator." (Parameter 'hintName')
```

This issue arises because I have two `SearchTask` types in my project, but they are in different namespaces. It seems that the generator is having trouble handling multiple types with the same name but different namespaces.

I would like to request that this issue be addressed in the official ReactiveUI repository, as it currently prevents me from using the Source Generators effectively.

### Step to reproduce

1. Create two types with the same name (e.g., `SearchTask`) in different namespaces.
2. Upgrade to `ReactiveUI.SourceGenerators` version 2.0.17.
3. Compile the project and observe the error.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI.SourceGenerators

### Expected behavior

The source generator should handle cases where multiple types share the same name but are in different namespaces without causing conflicts or errors.

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

2.0.17

**Comment by glennawatson** [comment]
Can you provide a small source code snippet if able of a class that's producing the error? 

Looks like maybe some unusual condition like nested classes or something like that. 

Cheers

**Comment by Soar360** [comment]
Try this:

https://github.com/Soar360/ReactiveUI.SourceGenerators.Fix131

![image](https://github.com/user-attachments/assets/868b32db-fb08-4755-8514-d8adadaf9377)

CSC: warning CS8785: The generator "ReactiveGenerator" failed to generate source. It will not affect output, but it may cause compilation errors. The exception type is "ArgumentException" with the message "The hintName 'SearchTask.Properties.g.cs' of the added source file must be unique within the generator. (Parameter 'hintName')".

and 

```
D:\src\test\ReactiveUI.SourceGenerators.Fix131\Demo\Demo>dotnet --list-sdks
6.0.100 [C:\Program Files\dotnet\sdk]
8.0.404 [C:\Program Files\dotnet\sdk]
9.0.100 [C:\Program Files\dotnet\sdk]
```

**Comment by glennawatson** [comment]
Appreciate it. We should have a fix out for this weekend.
