### ISSUE TITLE
Missing license and copyright notice for all MVVM Toolkit and PolySharp code

### ISSUE THREAD

**Issue by Sergio0694** [reactiveui/ReactiveUI.SourceGenerators#142]
Hey there! I noticed that #3 lifted pretty much the entire source generators from the [Microsoft MVVM Toolkit](https://github.com/CommunityToolkit/dotnet) without any 3rd party disclaimer notice and correct attribution. It's very easy to tell because the files are pretty much identical to my code in the .NET Community Toolkit repo. You can see how the file structure, file names, most type names, code structure, even the comments, are the same. The PR just renamed a bunch of APIs to match whatever ReactiveUI preferred. I'm a bit puzzled here because I'd imagine the author of the PR (@ChrisPulman) must have known where the code was coming from, yet the PR had no mentions whatsoever about the fact the code was not actually his.

The MVVM Toolkit is MIT licensed, meaning that it is ok for ReactiveUI to reuse parts of it. However, aside from the strict legal requirements, especially with this repo being part of the .NET Foundation, I would expect a higher bar with respect to contributions that reuse other open source code. That would include at the very least proper attribution, credits, etc. even when not necessarily mandated by the license itself. We should do better.

The same PR also lifted a whole lot of code from my other project [PolySharp](https://github.com/Sergio0694/PolySharp). Once again, with no 3rd party disclaimer notice and correct attribution. In this case it did keep the "PolySharp" name for the files, though not even sure if that was intentional at this point anyway. Not to mention that is not a valid form of attribution anyway.

cc. @glennawatson, I see you approved the PR but I assume you didn't know the code was not original at all.

I've updated the issue to clarify that I'm not implying that the project is legally breaching the license terms of the MIT license. I do see the MIT disclaimer in the file headers and in the repo license. This is not about what is strictly required for legal compliance, but rather about best practices about attributing other projects whose code is being reused.

**Comment by michael-hawker** [comment]
I did notice in #113 the Readme was updated, which in passing calls out referencing `PolySharp` in older projects (still not proper attribution, especially in the given context). However, it is also mis-attributed to some other fork which no longer exists ([vs the proper source by Sergio](https://github.com/Sergio0694/PolySharp)):

![image](https://github.com/user-attachments/assets/4fbde167-8132-4799-9dd9-5c4a7dad27f7)

The other Polyfill repo mentioned also no longer exists.

**Comment by glennawatson** [comment]
Yeah. If you like mind doing a PR updating the license and readme. 

Happy to attribute. 

The codebase has deviated a bit since the early days but like you said be good to attribute appropriately.

**Comment by glennawatson** [comment]
Btw I would do the PR myself but want to make sure we attribute your work correctly.

**Comment by glennawatson** [comment]
Also worth noting the project probably isn't part of the net foundation and that code is copy pasted from the main repo. .net foundation are licensed on a per repo basis so likely we will have to remove that notice too. 

So might be worth me raising the PR thinking about it. 

The source generator project I been a bit autopilot so you have my apologies for not picking up the attribution issue earlier etc.

**Comment by glennawatson** [comment]
Also worth noting the project probably isn't part of the net foundation and that code is copy pasted from the main repo. .net foundation are licensed on a per repo basis so likely we will have to remove that notice too. 

So might be worth me raising the PR thinking about it. 

The source generator project I been a bit autopilot so you have my apologies for not picking up the attribution issue earlier etc.

**Comment by glennawatson** [comment]
> I did notice in #113 the Readme was updated, which in passing calls out referencing `PolySharp` in older projects (still not proper attribution, especially in the given context). However, it is also mis-attributed to some other fork which no longer exists ([vs the proper source by Sergio](https://github.com/Sergio0694/PolySharp)):
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/4fbde167-8132-4799-9dd9-5c4a7dad27f7)
> 
> 
> 
> The other Polyfill repo mentioned also no longer exists.

I didn't add those as attributions just more references where people to click on so not really the intent.
