### ISSUE TITLE
[Bug]: Failed to AOT compile ReactiveUI.SourceGenerators.dll

### ISSUE THREAD

**Issue by nor0x** [reactiveui/ReactiveUI.SourceGenerators#19]
### Describe the bug 🐞

I'm using Reactive.UI.SourceGenerators in a .NET MAUI iOS project. Currently publishing the app for a store release fails at the AOT step with the following error message:

```pwsh
Tool /Users/runner/.dotnet/packs/Microsoft.NETCore.App.Runtime.AOT.osx-arm64.Cross.ios-arm64/8.0.7/Sdk/../tools/mono-aot-cross execution finished (exit code = 139).
          
/Users/runner/.dotnet/packs/Microsoft.iOS.Sdk/17.2.8078/targets/Xamarin.Shared.Sdk.targets(1216,3): error : Failed to AOT compile ReactiveUI.SourceGenerators.dll, the AOT compiler exited with code 139. [/Users/runner/work/project/MauiApp1.csproj::TargetFramework=net8.0-ios]
```

### Step to reproduce

1. create new .NET MAUI project (`dotnet new maui`)
2. add ReactiveUI.SourceGenerators package
3. publish project for release `dotnet publish MauiApp1.csproj -c Release -f net8.0-ios -r ios-arm64 -p:ArchiveOnBuild=true`

### Expected behavior

publish should finish successfully

### ReactiveUI Version

ReactiveUI.SourceGenerators 1.0.3

**Comment by ChrisPulman** [comment]
I am hopeful that this will be resolved with the next release, I should have generated the Attributes from the outset.
The next release will have no requirement to reference the build and will be a pure Analyser.
