### ISSUE TITLE
[Bug]: Generation fails with partial classes

### ISSUE THREAD

**Issue by denys-volodarskyi** [reactiveui/ReactiveUI.SourceGenerators#24]
### Describe the bug 🐞

The following sample repository shows that source generation fails when ReactiveCommand is used in different files of a partial class.

### Step to reproduce

Open project and build

### Reproduction repository

https://github.com/denys-volodarskyi/samples_reactiveui_srcgen

### Expected behavior

Normally it must compile without errors

### IDE

Visual Studio 2022

**Comment by ChrisPulman** [comment]
Thank you for raising this issue, I will take a look and see what I can do to resolve this.

**Comment by ChrisPulman** [comment]
@denys-volodarskyi This should be resolved with the next release. Thank you.
