### ISSUE TITLE
[Bug]: ReactiveCommand, CanExecute ignored

### ISSUE THREAD

**Issue by fubar-coder** [reactiveui/ReactiveUI.SourceGenerators#44]
### Describe the bug 🐞

I tried to use the new ReactiveCommandAttribute together with the "CanExecute" parameter, but it seems that this parameter is ignored.

### Step to reproduce

1. Create an `IObservable<bool>` field with name `_canContinue`
2. Create a function `void Continue()`
3. Apply the `ReactiveCommand(CanExecute = nameof(_canContinue))` attribute

### Reproduction repository

https://github.com/fubar-coder/ReactiveCommandCanExecuteBug

### Expected behavior

It should create a `ReactiveCommand` which uses `_canContinue` observable to determine whether the command can be executed.

### Screenshots 🖼️

As you can see, no reference to `_canContinue`:

![grafik](https://github.com/user-attachments/assets/c4a24ffb-a310-43d7-8005-3c3f4573dd8a)

### IDE

Visual Studio 2022

### Operating system

Windows 11

### Version

23H2

### Device

Laptop

### ReactiveUI Version

20.1.52

**Comment by ChrisPulman** [comment]
Hi thank you for raising this, I will get this resolved.

**Comment by ChrisPulman** [comment]
Please update to 1.1.31 to resolve this, thank you.
