### ISSUE TITLE
Make [ReactiveCommand] command properties notnull

### ISSUE THREAD

**Issue by mycroes** [reactiveui/ReactiveUI.SourceGenerators#46]
**Is your feature request related to a problem? Please describe.**

Having the commands declared as nullable results in additional code to either suppress nullable warnings or to apply null-checks. Obviously the commands are only null when `InitializeCommands` has not been called, which is an obvious programming error.

**Describe the solution you'd like**

I'd like the command properties to no longer be defined as nullable. Preferably I'd also like them not to have a null value at all, see last paragraph for possible implementation.

**Describe alternatives you've considered**

N/A.

**Describe suggestions on how to achieve the feature**

Instead of relying on `InitializeCommands` to set the command properties, declare them using a defined backing field (which should probably have `[EditorBrowsable(false)]`:

```csharp
private ReactiveCommand<Unit, RepositoryStatus>? _refreshCommand;

public ReactiveCommand<Unit, RepositoryStatus> RefreshCommand
{
    get
    {
        return _refreshCommand ??= ReactiveCommand.CreateFromTask(Refresh);
    }
}

[ReactiveCommand]
private Task<RepositoryStatus> Refresh()
{
    throw new NotImplementedException();
}
```

**Comment by ChrisPulman** [comment]
Please update to 1.1.31 to resolve this, thank you.
