### ISSUE TITLE
[Bug]: namespace error

### ISSUE THREAD

**Issue by ethpch** [reactiveui/ReactiveUI.SourceGenerators#54]
### Describe the bug 🐞

Build Avalonia project always report CS0246 error. It seems like namespace is not resolved for custom classes. In generated files there are always no using statements for `Avalonia` namespace and `Project.ViewModels` namespace.

### Step to reproduce

1. Create a new Avalonia C# Project, enable ReactiveUI and add this package to the project by nuget
2. Open MainView.axaml.cs
3. Add `[IViewFor(nameof(MainViewModel))]` for `MainView`
4. Build, and see error

### Expected behavior

No build errors

### Screenshots 🖼️

![image](https://github.com/user-attachments/assets/b5ae803f-7847-4dbf-bfa9-2ef7f2fdad50)

### IDE

Visual Studio 2022

### Operating system

Windows 11 Pro

### Version

23H2

### Device

Desktop

### ReactiveUI Version

18.3.1, by avalonia

### Additional information ℹ️

Changing attribute to full declaration like `[IViewFor($"ViewModels.{nameof(MainViewModel)}")]` can avoid such issue, but `StyledProperty` and `AvaloniaPropertyChangedEventArgs` belongs to `Avalonia` namespace. Please fix this namespace error for Avalonia, and add more information at readme.

![image](https://github.com/user-attachments/assets/a6862d0a-0e96-407f-8884-3b767507e680)

Maybe [Generic Attribute](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/generic-attributes) could help, or scan the full assembly to find the correct class and its namespace. I'm not familar with SourceGenerators.

**Comment by ChrisPulman** [comment]
We will release this update soon, if you wanted to try it you could download the related nuget package from the CI build https://github.com/reactiveui/ReactiveUI.SourceGenerators/actions/runs/11043024970/artifacts/1979778639

Thank you

**Comment by ethpch** [comment]
Thanks for your quick response!

I have tried the latest version and the generic attribute works as expected. But the generated code still lacks namespace `Avalonia` so project cannot get built, which `StyledProperty` and `AvaloniaPropertyChangedEventArgs` belongs to.

I have uploaded [minimal project](https://github.com/ethpch/ReactiveUI.SourceGenerators.Test). This project is created step by step, a minimal Avalonia C# Project with `[IViewFor<ViewModels.MainViewModel>]` attribute to `MainView` class.

And the [Generic Attribute tracking issue](https://github.com/dotnet/csharplang/issues/124#issue-207966111) shows this feature is still in progress, and [it won't be backported to .NET Framework](https://github.com/dotnet/csharplang/issues/124#issuecomment-1350082734). Please evaluate its compatibility.

**Comment by ethpch** [comment]
I have checked default templates for `Maui`, `WinForm` and `Wpf`, please check [this project](https://github.com/ethpch/ReactiveUI.SourceGenerators.IViewForTest).

As a result, `Maui` and `WinForm` works well, but there are some issues with `Avalonia` and `Wpf`.

`Avalonia` is namespace error, and it cannot get built.

`Wpf` can get built, but breaks on `MainWindow.InitializeComponent()`. The error message is `ArgumentException: “IViewFor``1”类型必须派生自 DependencyObject。` 

Check the generated code, the ViewModelProperty is defined as `public static readonly DependencyProperty ViewModelProperty = DependencyProperty.Register(nameof(ViewModel), typeof(WpfApp1.MainViewModel), typeof(IViewFor<WpfApp1.MainViewModel>), new PropertyMetadata(null));`.

Parameter 3 of `DependencyProperty.Register` is `ownerType`. It should be `typeof(MainWindow)` here, or `typeof(SomeControl)`, not `typeof(IViewFor<WpfApp1.MainViewModel>)`.

![image](https://github.com/user-attachments/assets/4269cd9a-2e6d-4588-9042-41c05920fa6b)

There are some troubles for default templates for WinUI3([#4693](https://github.com/microsoft/WindowsAppSDK/issues/4698), [#4734](https://github.com/microsoft/WindowsAppSDK/issues/4734)) and UWP(strange nullable settings), I cannot test these frames.

Should I open another issue for this?

I hope the information can help this project.

**Comment by ChrisPulman** [comment]
Thank you very much for this feedback, I will reopen this and re visit the solution.

**Comment by ChrisPulman** [comment]
Hi, I believe that #65 has now resolved this issue, thank you very much for the pointers to the issues.
We will try to release this in the next few days.
