### ISSUE TITLE
Disable the RXUISG0016 analyzer for read-only properties

### ISSUE THREAD

**Issue by PremekTill** [reactiveui/ReactiveUI.SourceGenerators#66]
**Is your feature request related to a problem? Please describe.**

When including ReactiveUI.SourceGenerators in a project, the RXUISG0016 analyser marks public properties on ReactiveObjects and offers to convert them to Reactive fields. However, this change does not make much sense for read-only properties - since they can never change, there is no need to wire them up for INPC. Additionally, the quick fix converts them to standard read-write fields, removing the original behaviour (and they cannot be made readonly due to the attribute requirements).

**Describe the solution you'd like**

Removing the false positives by only triggering RXUISG0016 for read-write properties.

**Describe alternatives you've considered**

Disabling the analyser globally via editorconfig - this obviously removes the issue of false positives, but loses the convenience of using the quick fixes when appropriate. Also, the analyser is only at "hint" level by default, so it can be simply ignored when not desirable - but the false positives still create unnecessary IDE noise if nothing more.

**Comment by ChrisPulman** [comment]
Thank you for this feedback I have also spotted the false positives which can be misleading and if a fix all operation were carried out would lead to undesired results. I will rework this to be more friendly.
