### ISSUE TITLE
OAPH cannot be created outside of constructor (i.e. in WhenActivated clause)

### ISSUE THREAD

**Issue by sdijoseph** [reactiveui/ReactiveUI.SourceGenerators#75]
**Is your feature request related to a problem? Please describe.**

It currently doesn't seem possible to subscribe to a OAPH outside of the constructor of the view model. This is desirable when you want to unsubscribe to a OAPH when the view model is deactivated. For example:

```
using System.Reactive.Disposables;
using System.Reactive.Linq;
using ReactiveUI;
using ReactiveUI.SourceGenerators;

namespace MyNameSpace;

public partial class TestViewModel : ReactiveObject, IActivatableViewModel
{
    public ViewModelActivator Activator { get; } = new();

    [ObservableAsProperty] private bool _test;

    public TestViewModel()
    {
        this.WhenActivated(disposables =>
        {
            _testHelper = Observable.Return(true)
                .ToProperty(this, x => x.Test)
                .DisposeWith(disposables);
        });
    }
}
```

Right now, this does not compile since ```_testHelper``` is defined as ```readonly```:

```
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace MyNameSpace
{
    /// <inheritdoc/>
    partial class TestViewModel
    {
        /// <inheritdoc cref="_testHelper"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        private readonly ReactiveUI.ObservableAsPropertyHelper<bool> _testHelper;
        /// <inheritdoc cref="_test"/>
        [global::System.CodeDom.Compiler.GeneratedCode("ReactiveUI.SourceGenerators.ObservableAsPropertyGenerator", "1.1.0.0")]
        [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
        public bool Test { get => _test = (_testHelper?.Value ?? _test); }
    }
}
```

**Describe the solution you'd like**

I would like to be able to subscribe to OAPH within a WhenActivated clause, so that I can clean-up the subscription on view model deactivation.

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

It seems like a solution that should work is to define any ```ObservableAsPropertyHelper<T>``` as ```ObservableAsPropertyHelper<T>?```, and then remove the ```readonly``` modifier. I have not tested this myself yet, as I wanted to make sure there wasn't already a way of dealing with this scenario that I've missed.

**Additional context**

**Comment by Geccoka** [comment]
Here is a solution/workaround i use to overcome that:

```
public partial class AttendedEvent : ReactiveObject, IActivatableViewModel
{
    private readonly CompositeDisposable _compositeDisposable = new();

    public AttendedEvent(ObservableEvent observableEvent)
    {
        observableEvent.CurrentSpeaker
            .ToProperty(this, x => x.CurrentSpeaker, out _currentSpeakerHelper)
            .DisposeWith(_compositeDisposable);

        this.WhenActivated(disposables =>
        {
            Disposable
                .Create(_compositeDisposable.Dispose)
                .DisposeWith(disposables);
        });
    }
}
```

**Comment by sdijoseph** [comment]
> Here is a solution/workaround i use to overcome that:
> 
> ```
> public partial class AttendedEvent : ReactiveObject, IActivatableViewModel
> {
>     private readonly CompositeDisposable _compositeDisposable = new();
> 
>     public AttendedEvent(ObservableEvent observableEvent)
>     {
>         observableEvent.CurrentSpeaker
>             .ToProperty(this, x => x.CurrentSpeaker, out _currentSpeakerHelper)
>             .DisposeWith(_compositeDisposable);
> 
>         this.WhenActivated(disposables =>
>         {
>             Disposable
>                 .Create(_compositeDisposable.Dispose)
>                 .DisposeWith(disposables);
>         });
>     }
> }
> ```
> 
> Edit:
> 
> Just when i wrote this comment it came to my mind that the WhenActivated can be simplified to this:
> 
> ```
>         this.WhenActivated(disposables =>
>         {
>             _compositeDisposable.DisposeWith(disposables);
>         });
> ```

I think the issue with this is that the ```ToProperty``` call only happens once in the constructor. So if our view model is created once per application lifetime, the OAPH subscription will get disposed on the first deactivation, and then never re-subscribed.

**Comment by Geccoka** [comment]
Yes, in that scenario this solution won't work. But just for curiosity, in what use case do you create your viewmodels once per app lifetime? I create them when the associated page becomes visible. If the same page is visited again, i create a new one. But i develops web apps in Blazor, maybe this is a different use case.

**Comment by sdijoseph** [comment]
> Yes, in that scenario this solution won't work. But just for curiosity, in what use case do you create your viewmodels once per app lifetime? I create them when the associated page becomes visible. If the same page is visited again, i create a new one. But i develop web apps in Blazor, maybe this is a different use case.

I mainly develop Avalonia desktop applications, and we typically register the view models once at startup in our DI container.

**Comment by Micha-kun** [comment]
It could be solved if it could be configured as this:
