### ISSUE TITLE
Strip `Async` suffix from Generated Commands

### ISSUE THREAD

**Issue by michaelstonis** [reactiveui/ReactiveUI.SourceGenerators#78]
**Describe the solution you'd like**
When using the `ReactiveCommand` attribute, it would be nice if the generated command stripped out the Async suffix from the command name when using methods that end with Async.

For example.

```
[ReactiveCommand]
private Task InitializeAsync()
{
	...
}
```

Currently, this would result in a command named `InitializeAsyncCommand`. The desired functionality would be to have a command named `InitializeCommand` generated.

The MVVM Toolkit does something similar with [this implementation](https://github.com/CommunityToolkit/dotnet/blob/cb478f1faa2e37017a98037af527a962abc4f5d7/src/CommunityToolkit.Mvvm.SourceGenerators/Input/RelayCommandGenerator.Execute.cs#L492).

**Describe alternatives you've considered**
The workaround right now is to just omit the `Async` suffix on methods that return tasks. This can vary from team to team as to whether they add this suffix.

**Comment by ChrisPulman** [comment]
Thank you Michael, this has been added.
