### ISSUE TITLE
ReactiveCommand support for private naming convention

### ISSUE THREAD

**Issue by zacfromaustinpowder** [reactiveui/ReactiveUI.SourceGenerators#9]
**Is your feature request related to a problem? Please describe.**

My private method named with an underscore generates a public property with an underscore as well. For example, the method below would generate `_refreshCommand` instead of `RefreshCommand`.

```cs
[ReactiveCommand]
async Task _refresh() {}
```

**Describe the solution you'd like**

Add a check to see if the method name starts with an underscore + lowercase, then replace with not underscore + uppercase.

**Describe suggestions on how to achieve the feature**

In `ReactiveCommandGenerator.Execute.cs` modify line 192 to apply a transformation to the method name string. e.g.

```cs
var methodName = methodSymbol.Name;
if (methodName.Length > 1 && methodName[0] == '_' && char.IsLower(methodName[1]))
    methodName = char.ToUpper(methodName[1]) + methodName.Substring(2);

commandExtensionInfos.Add(new(
    methodName,
    /*...*/));
```

**Comment by ChrisPulman** [comment]
Thank you for this, I will add this or similar into the next Release version.

**Comment by ChrisPulman** [comment]
V1.1.26 has been released, please update
