### ISSUE TITLE
NuGet Release Schedule

### ISSUE THREAD

**Issue by PremekTill** [reactiveui/ReactiveUI.SourceGenerators#91]
**Is your feature request related to a problem? Please describe.**

I've been running into the issue described in #51 for quite some time. The issue was (hopefully) fixed by #52 about a month ago, but there has not been a NuGet release since it got merged. Do you have some plans as to when the next release might come?

**Describe alternatives you've considered**

To circumvent the issue for now, I have considered disabling the offending analyzers through editorconfig. Unfortunately, since the warning is not reported by the analyzer, but rather inside the analyzer, it does not include its diagnostic code &ndash; I know that the AsyncVoidReturningReactiveCommandMethodAnalyzer, PropertyToReactiveFieldAnalyzer and UnsupportedCSharpLanguageVersionAnalyzer are failing to build, but I do not know the corresponding codes to disable them. It would be nice to include a short list of provided analyzers (at least their name + diagnostic code) somewhere in the documentation.

**Comment by ChrisPulman** [comment]
The documentation on this Repository is up to date and released with each nuget package, we will update the main ReactiveUI website with the updates from the release from yesterday. There has been a release 2.0.9 another will follow shortly to resolve some of the reported issues with some various use cases.
