### ISSUE TITLE
[Bug]: If you use MSBuilde for .Net 9, using this package makes the build stuck.

### ISSUE THREAD

**Issue by WCKYWCKF** [reactiveui/ReactiveUI.SourceGenerators#99]
### Describe the bug 🐞

In Rider, using this package makes the build stuck.

### Step to reproduce

1. Rider version 2024.2 or later
2. Create a project using the avaloniaUI cross-platform template（MVVM use ReactiveUI）
3. Join this pack
4. Start building your project

### Reproduction repository

https://github.com/WCKYWCKF/AvaloniaApplication1

### Expected behavior

The build will get stuck all the time

### IDE

Rider Windows

### Operating system

Win11 H2

### Version

1.1.31

### ReactiveUI Version

20.1.63

**Comment by WCKYWCKF** [comment]
However, this is not an issue in version 1.0.3 and below

**Comment by WCKYWCKF** [comment]
This seems to be an issue with MSBuild.This issue only exists in MSBuild for .net 9.

**Comment by glennawatson** [comment]
Let's keep this open anyway for testing. .net 9 is release is 12th November so we want to make sure it is compatible.

**Comment by WCKYWCKF** [comment]
CSC: Warning CS8032 : 无法从 C:\Users\wckfx\.nuget\packages\reactiveui.sourcegenerators\1.1.31\analyzers\dotnet\cs\ReactiveUI.SourceGenerators.dll 创建分析器 ReactiveUI.SourceGenerators.AsyncVoidReturningReactiveCommandMethodAnalyzer 的实例: 调用的目标发生了异常。。
1>CSC: Warning AD0001 : 分析器“ReactiveUI.SourceGenerators.CodeAnalyzers.PropertyToReactiveFieldAnalyzer”引发类型为“System.TypeInitializationException”的异常，并显示消息““ReactiveUI.SourceGenerators.Diagnostics.DiagnosticDescriptors”的类型初始值设定项引发异常。”。
1>CSC: Warning AD0001 : 分析器“ReactiveUI.SourceGenerators.UnsupportedCSharpLanguageVersionAnalyzer”引发类型为“System.TypeInitializationException”的异常，并显示消息““ReactiveUI.SourceGenerators.Diagnostics.DiagnosticDescriptors”的类型初始值设定项引发异常。”。

**Comment by glennawatson** [comment]
Thanks

**Comment by WCKYWCKF** [comment]
This question may have arisen before #51

**Comment by WCKYWCKF** [comment]
> Thanks

You're welcome, I'm a big fan of RxUI. This package allows me to enjoy the convenience of the CommunityMVVM package in RxUI.

**Comment by nor0x** [comment]
I have the same issue with .NET MAUI on .NET 9

i'm using
`<PackageVersion Include="ReactiveUI.SourceGenerators" Version="1.1.31" />` which makes the `CoreCompile` task run forever

Here is a repro:
[MauiApp1.zip](https://github.com/user-attachments/files/17577569/MauiApp1.zip)

and a binlog:
[msbuild.binlog.zip](https://github.com/user-attachments/files/17577576/msbuild.binlog.zip)

**Comment by WCKYWCKF** [comment]
> I have the same issue with .NET MAUI on .NET 9我在.NET MAUI 的.NET 9 上遇到相同的问题
> 
> i'm using 我在使用 `<PackageVersion Include="ReactiveUI.SourceGenerators" Version="1.1.31" />` which makes the `CoreCompile` task run forever `<PackageVersion Include="ReactiveUI.SourceGenerators" Version="1.1.31" />` 这使得 `CoreCompile` 任务永远运行
> 
> Here is a repro: 这里是一个可复现的问题： [MauiApp1.zip](https://github.com/user-attachments/files/17577569/MauiApp1.zip)
> 
> and a binlog: 和一个 binlog： [msbuild.binlog.zip](https://github.com/user-attachments/files/17577576/msbuild.binlog.zip)

If you are using Rider, please set MSBuild to use .Net 8 or something else.

**Comment by WCKYWCKF** [comment]
> i'm currently using vscode - not sure if there is such an option我目前在使用 VSCode - 不确定是否有这样的选项

All in all, this issue can be fixed as long as you don't use MSBuild for .net 9.

**Comment by glennawatson** [comment]
@ChrisPulman theres that analyser stating updates to projects. This may be a possible fix not to use workspaces projects.

**Comment by glennawatson** [comment]
I suspect that it might be better with the latest release, since we followed some recommended patterns for packages to include.

**Comment by WCKYWCKF** [comment]
This issue has been fixed, congratulations!
